name: CI

on:
  push:
    paths:
      - "setup.py"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: sudo apt-get install -y libzmq3-dev

      - name: Create virtual environment
        run: |
          python -m venv .venv
          echo ".venv/" >> .gitignore
          source .venv/bin/activate
      - name: Build and Test
        run: |
          python -m pip install --upgrade pip
          pip install maturin
          maturin develop

      - name: Build Wheels
        run: |
          source .venv/bin/activate
          pip install maturin
          maturin build --release --strip --no-sdist -i python
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
